using Unity.Entities;
using Unity.Mathematics;

namespace Laboratory.Core.Ragdoll
{
    #region Hit Events
    
    /// <summary>
    /// Component data representing a hit event on a ragdoll bone.
    /// Contains information about the target bone, applied force, and timing for blend recovery.
    /// </summary>
    public struct HitEvent : IComponentData
    {
        /// <summary>
        /// Entity representing the bone that was hit.
        /// </summary>
        public Entity BoneEntity;
        
        /// <summary>
        /// Force vector applied to the bone in world space.
        /// </summary>
        public float3 Force;
        
        /// <summary>
        /// Time delay in seconds before starting the blend back to animation.
        /// </summary>
        public float DelayBeforeBlend;
    }
    
    /// <summary>
    /// Component data representing a collision event between a ragdoll bone and the environment.
    /// Used for triggering impact effects and sound reactions.
    /// </summary>
    public struct CollisionEvent : IComponentData
    {
        /// <summary>
        /// Entity of the bone that collided with the environment.
        /// </summary>
        public Entity BoneEntity;
        
        /// <summary>
        /// Force generated by the collision impact.
        /// </summary>
        public float3 CollisionForce;
    }
    
    /// <summary>
    /// Component data representing a character landing event.
    /// Triggered when the character makes contact with the ground after being airborne.
    /// </summary>
    public struct LandingEvent : IComponentData
    {
        /// <summary>
        /// Entity representing the character that landed.
        /// </summary>
        public Entity CharacterEntity;
    }
    
    #endregion
    
    #region Blend Data
    
    /// <summary>
    /// Component data storing interpolation information for smooth ragdoll-to-animation blending.
    /// Contains starting transform state and timing data for the blend process.
    /// </summary>
    public struct BlendData : IComponentData
    {
        /// <summary>
        /// Starting world position when blend process began.
        /// </summary>
        public float3 StartPosition;
        
        /// <summary>
        /// Starting world rotation when blend process began.
        /// </summary>
        public quaternion StartRotation;
        
        /// <summary>
        /// Current elapsed time since blend process started.
        /// </summary>
        public float Timer;
        
        /// <summary>
        /// Total duration of the blend process in seconds.
        /// </summary>
        public float Duration;
    }
    
    #endregion
    
    #region Tag Components
    
    /// <summary>
    /// Tag component marking entities that should blend back from ragdoll to animation.
    /// Processed by BlendBackSystem to create smooth transitions.
    /// </summary>
    public struct BlendBackTag : IComponentData 
    { 
        // Empty tag component - no data needed
    }
    
    /// <summary>
    /// Tag component marking bones or entities participating in partial ragdoll physics.
    /// Used by systems to identify which entities can be affected by ragdoll forces.
    /// </summary>
    public struct PartialRagdollTag : IComponentData 
    { 
        // Empty tag component - no data needed
    }
    
    #endregion
}
