using Unity.Entities;
using Unity.Mathematics;

namespace Laboratory.Core.Ragdoll
{
    #region Hit Events

    /// <summary>
    /// Component representing a hit event for ragdoll physics.
    /// Contains information about the force applied and the affected bone entity.
    /// </summary>
    public struct HitEvent : IComponentData
    {
        /// <summary>
        /// The entity representing the bone that was hit
        /// </summary>
        public Entity BoneEntity;

        /// <summary>
        /// The force vector applied to the ragdoll
        /// </summary>
        public float3 Force;

        /// <summary>
        /// Delay before blending back to animation (in seconds)
        /// </summary>
        public float DelayBeforeBlend;

        /// <summary>
        /// The impact point in world space
        /// </summary>
        public float3 ImpactPoint;

        /// <summary>
        /// The magnitude of the impact force
        /// </summary>
        public float ImpactMagnitude;
    }

    /// <summary>
    /// Component representing a collision event for ragdoll sound effects.
    /// Triggered when ragdoll collides with environment objects.
    /// </summary>
    public struct CollisionEvent : IComponentData
    {
        /// <summary>
        /// The entity that experienced the collision
        /// </summary>
        public Entity CollisionEntity;

        /// <summary>
        /// The collision point in world space
        /// </summary>
        public float3 CollisionPoint;

        /// <summary>
        /// The collision normal vector
        /// </summary>
        public float3 CollisionNormal;

        /// <summary>
        /// The collision impulse magnitude
        /// </summary>
        public float CollisionMagnitude;

        /// <summary>
        /// The velocity at the time of collision
        /// </summary>
        public float3 CollisionVelocity;

        /// <summary>
        /// Entity of the bone that collided with the environment.
        /// </summary>
        public Entity BoneEntity;

        /// <summary>
        /// Force generated by the collision impact.
        /// </summary>
        public float3 CollisionForce;
    }

    /// <summary>
    /// Component representing a landing event for ragdoll sound effects.
    /// Triggered when ragdoll lands on a surface after falling.
    /// </summary>
    public struct LandingEvent : IComponentData
    {
        /// <summary>
        /// Entity representing the character that landed.
        /// </summary>
        public Entity CharacterEntity;

        /// <summary>
        /// The entity that landed
        /// </summary>
        public Entity LandingEntity;

        /// <summary>
        /// The landing point in world space
        /// </summary>
        public float3 LandingPoint;

        /// <summary>
        /// The surface normal where the landing occurred
        /// </summary>
        public float3 SurfaceNormal;

        /// <summary>
        /// The impact velocity magnitude
        /// </summary>
        public float ImpactVelocity;

        /// <summary>
        /// The height from which the entity fell
        /// </summary>
        public float FallHeight;
    }
    
    
    
    #endregion
    
    #region Blend Data
    
    /// <summary>
    /// Component data storing interpolation information for smooth ragdoll-to-animation blending.
    /// Contains starting transform state and timing data for the blend process.
    /// </summary>
    public struct BlendData : IComponentData
    {
        /// <summary>
        /// Starting world position when blend process began.
        /// </summary>
        public float3 StartPosition;
        
        /// <summary>
        /// Starting world rotation when blend process began.
        /// </summary>
        public quaternion StartRotation;
        
        /// <summary>
        /// Current elapsed time since blend process started.
        /// </summary>
        public float Timer;
        
        /// <summary>
        /// Total duration of the blend process in seconds.
        /// </summary>
        public float Duration;
    }
    
    #endregion
    
    #region Tag Components
    
    /// <summary>
    /// Tag component marking entities that should blend back from ragdoll to animation.
    /// Processed by BlendBackSystem to create smooth transitions.
    /// </summary>
    public struct BlendBackTag : IComponentData 
    { 
        // Empty tag component - no data needed
    }
    
    /// <summary>
    /// Tag component marking bones or entities participating in partial ragdoll physics.
    /// Used by systems to identify which entities can be affected by ragdoll forces.
    /// </summary>
    public struct PartialRagdollTag : IComponentData 
    { 
        // Empty tag component - no data needed
    }
    
    #endregion
}
