using UnityEngine;
using UnityEngine.InputSystem;

namespace Laboratory.Models.Input
{
    /// <summary>
    /// PlayerControls class - typically auto-generated by Unity Input System
    /// This is a manual implementation for compilation purposes
    /// </summary>
    public class PlayerControls : MonoBehaviour
    {
        [Header("Input Actions")]
        public InputActionAsset inputActions;
        
        // Input Maps
        public InputActionMap playerActionMap;
        public InputActionMap uiActionMap;
        
        // InGame accessor for compatibility
        public PlayerInputActions InGame => new PlayerInputActions(this);
        
        // Player Actions
        public InputAction moveAction;
        public InputAction lookAction;
        public InputAction jumpAction;
        public InputAction attackAction;
        public InputAction crouchAction;
        public InputAction runAction;
        public InputAction interactAction;
        public InputAction aimAction;
        public InputAction reloadAction;
        
        private void Awake()
        {
            if (inputActions != null)
            {
                // Get action maps
                playerActionMap = inputActions.FindActionMap("Player");
                uiActionMap = inputActions.FindActionMap("UI");
                
                // Get individual actions
                if (playerActionMap != null)
                {
                    moveAction = playerActionMap.FindAction("Move");
                    lookAction = playerActionMap.FindAction("Look");
                    jumpAction = playerActionMap.FindAction("Jump");
                    attackAction = playerActionMap.FindAction("Attack");
                    crouchAction = playerActionMap.FindAction("Crouch");
                    runAction = playerActionMap.FindAction("Run");
                    interactAction = playerActionMap.FindAction("Interact");
                    aimAction = playerActionMap.FindAction("Aim");
                    reloadAction = playerActionMap.FindAction("Reload");
                }
            }
        }
        
        public void Enable()
        {
            inputActions?.Enable();
        }
        
        public void Disable()
        {
            inputActions?.Disable();
        }
        
        private void OnEnable()
        {
            Enable();
        }
        
        private void OnDisable()
        {
            Disable();
        }
        
        public void Dispose()
        {
            if (inputActions != null)
            {
                inputActions.Disable();
                // InputActionAsset doesn't have Dispose method, just disable it
                // Actual disposal is handled by Unity's lifecycle
            }
        }
    }
    
    /// <summary>
    /// Wrapper class to provide InGame input actions
    /// </summary>
    public class PlayerInputActions
    {
        private PlayerControls controls;
        
        public PlayerInputActions(PlayerControls playerControls)
        {
            controls = playerControls;
        }
        
        public InputAction Move => controls.moveAction;
        public InputAction Look => controls.lookAction;
        public InputAction Jump => controls.jumpAction;
        public InputAction Attack => controls.attackAction;
        public InputAction Roll => controls.crouchAction; // Using crouch as roll for compatibility
        public InputAction WeaponSkill => controls.aimAction;
        public InputAction CharSkill => controls.interactAction;
    }
}
